### ISSUE TITLE
Implementing TypedValue and the git dependency on gazebo

### ISSUE THREAD

**Issue by anp** [facebookexperimental/starlark-rust#13]
It looks like right now to `impl TypedValue` that my type needs to also `impl AsTypedValue` and by implication `AnyLifetime`. IIUC, `AnyLifetime` is defined in gazebo which is published to crates.io but starlark uses it via git. So my crate needs to depend directly on both starlark and gazebo via two git deps. IMO in an ideal world the derive would come from crates.io or would be re-exported by the starlark crate. Do either of those options seem reasonable?

Separately, I think it would be nice if this repo's Cargo.toml could specify the exact gazebo revision it uses, but I'm not sure if y'all's open source export tooling can wire that up correctly. Without specifying the revision it's going to be hard to bisect through the crate's history using cargo. ~~I *think* Cargo will support revision pins correctly so if I ever need to hold back starlark I should still be able to convince it to use an older compatible gazebo revision, but it would be easiest if starlark's commits included pointers to compatible gazebo commits.~~

EDIT: It seems Cargo gives me two different instances of gazebo if I specify a revision in my Cargo.toml without one being specified in starlarks. From Cargo.lock:

```
[[package]]
name = "gazebo"
version = "0.1.0"
source = "git+https://github.com/facebookincubator/gazebo?rev=604500f#604500f2775efa3c36bb53b5241a6911547fabdb"
dependencies = [
 "gazebo_derive 0.1.0 (git+https://github.com/facebookincubator/gazebo?rev=604500f)",
]

[[package]]
name = "gazebo"
version = "0.1.0"
source = "git+https://github.com/facebookincubator/gazebo#604500f2775efa3c36bb53b5241a6911547fabdb"
dependencies = [
 "gazebo_derive 0.1.0 (git+https://github.com/facebookincubator/gazebo)",
]
```

Which IIUC means that until starlark specifies a revision for gazebo that I can't pin a starlark version that uses an incompatible gazebo API. Is there a way to include the revision in starlark/Cargo.toml?

**Comment by ndmitchell** [comment]
Both of your ideas seem reasonable. I think us relying on an unreleased version of Gazebo, which convenient for us, is a bit of a pain for everyone else. I'll push out a new release of Gazebo tomorrow, and pin us to a release, and do that going forward. Reexporting the AnyLifetime and few other types we rely on (ARef probably) seems like a good idea to simplify things for downstream users, it should only be a handful of things.

I still don't see why Cargo has picked different github versions for the two. Does cargo update fix that?

FWIW, we hope to make a release of Starlark in the next week or two, meaning you can rely entirely on Crates.io.

**Comment by anp** [comment]
All great news!

**Comment by anp** [comment]
After catching up on https://github.com/facebookexperimental/starlark-rust/issues/14, I see that `starlark_immutable_value!` impls `AnyLifetime` for me, so it's possible that the ergonomic concern is moot. I think the issues around pinning to old starlark versions should be resolved by publishing to crates.io because it won't allow git deps. Thanks for the prompt response!

**Comment by anp** [comment]
Further update: I think that the macro will still need `gazebo` to be available in the root namespace even if I don't need to import the derive directly. Maybe starlark could re-export gazebo without docs and then use that re-exported API in `starlark_immutable_value`?

**Comment by ndmitchell** [comment]
See https://github.com/facebookexperimental/starlark-rust/blob/4ea312ce2107644fff2a895054c3fae3d64c4722/starlark/src/macros/mod.rs#L121 - `starlark_immutable_value` actually uses `$crate::__macro_refs::any_lifetime!`, and we export the macros we use at https://github.com/facebookexperimental/starlark-rust/blob/4ea312ce2107644fff2a895054c3fae3d64c4722/starlark/src/lib.rs#L242-L245. So that should mostly fix it for you.

Note that this change landed appeared in the last week or so - if you checked previously, you would have needed gazebo in scope.

**Comment by anp** [comment]
Nice! I suspect there may be another dependency hiding in the macro stack, because I'm at https://github.com/facebookexperimental/starlark-rust/commit/8a8523fc4d7700cdea6cf8a31a56d29ee7be4764 and I get this error when I remove `gazebo` from my Cargo.toml:

```
error[E0433]: failed to resolve: use of undeclared crate or module `gazebo`
   --> src/builtins/command.rs:139:1
    |
139 | starlark_immutable_value!(Output);
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `gazebo`
```

**Comment by ndmitchell** [comment]
Ah, we use gazebo for ARef. That's one of the things that needs exposing.

**Comment by ndmitchell** [comment]
I think this is all fixed now. In particular:

1. We expose ARef and AnyLifetime from starlark::value.
2. We use those definitions in the macros.
3. We depend on Gazebo 0.2.0, rather than a git version.

Of those, 3 should make it easy to have a Gazebo dependency too. 2 should make it so our macros don't add a Gazebo dependency automatically. 1 might make it so you don't need a Gazebo dependency, but I'm less sure - in practice you might need the `any_lifetime!` macro or similar, which we don't export. If you come up with a list of what needs exposing in practice, we can export a few more things, but I think at a certain point we'll suggest people just use Gazebo as an explicit dependency.
