### ISSUE TITLE
Documentation should include examples implementing TypedValue

### ISSUE THREAD

**Issue by anp** [facebookexperimental/starlark-rust#14]
It would be awesome if there were a canonical example so I could know if I'm doing it correctly! The crate root's docs cover calling Rust functions, and I think it would be nice to have an extended version of that example which returns a Rust-defined type.

**Comment by ndmitchell** [comment]
Is f46450e6f0c4771e6f0576f0c552b39d0bb20f10 what you were after? (Only arrived a day or so ago) That is an example of implementing TypedValue, but only works for "simpler" typed values that don't themselves include Value's. If you want to go more complex, our thoughts were to direct people at https://github.com/facebookexperimental/starlark-rust/blob/master/starlark/src/values/types/record.rs, and add some comments to it. Does that give you approximately everything you were after? I think some words attached to TypedValue would be good too.

This is definitely one of the harder things in Rust Starlark. I can't see good ways to make it simpler (which had been the goal...), so it looks like the alternative has to be documenting it better.

**Comment by anp** [comment]
Ah, I'm not sure how my local docs missed that when re-generating after a pull, but yes that gets me much closer.

The other things I'm still poking at are how to correctly impl `UnpackValue` so that my `TypedValue`s can be accepted as function arguments and how to define a function as a method (attribute?) on that type.

**Comment by ndmitchell** [comment]
With `starlark_value_immutable` you get a free `UnpackValue`. If not, you just need to say how to convert a `Value` to a particular type, so it shouldn't be too complicated.

For methods hanging off a type, if they are a fixed set of methods, use `GlobalsStatic` and `get_members`. https://github.com/facebookexperimental/starlark-rust/blob/master/starlark/src/environment/globals.rs#L136-L144. You can see a few examples of that in the repo (e.g. `List`, `Struct` etc)

**Comment by anp** [comment]
> With starlark_value_immutable you get a free UnpackValue. If not, you just need to say how to convert a Value to a particular type, so it shouldn't be too complicated.

Ah, I see how this works. `starlark_immutable_value!(pub Foo)` generates a `RefFoo` type which implements `UnpackValue` and `Deref<Target=Foo>`. Would probably be good to explain this in the docs for the macro and include an example of its usage.

**Comment by ndmitchell** [comment]
> Would probably be good to explain this in the docs for the macro and include an example of its usage.

Agreed - unfortunately using macros for these things makes it pretty hard to figure out what is going on, other than explicit docs. I'd rather we didn't use macros, but can't figure out a way to achieve that.

**Comment by ndmitchell** [comment]
All documented now! 06ca29a964e02145e838f5f37bf5be575d83a9ea - in fact I've taken the time to document the entire library. In doing so, I changed a bunch of names to make them reflect what they do now, rather than what they did when they were inherited - so TypedValue is now StarlarkValue etc. I also simplified the macros to make their explanations easier - so for example there is no `RefFoo` anymore, but you can just use `ARef<Foo>` instead, which implements the normal traits, and everything works.

Sorry for the breakage that will cause your code, but I'm hoping to release within a week, and those names are now considered more stable - they might change in future, but my bar for breaking existing users has gone way up. If anything in the renamings aren't clear, or the docs aren't enough to figure out how these things work, please do shout.

**Comment by anp** [comment]
Hey, that's great news! A little breakage early in the crate's lifecycle is a small price to pay for clear names and docs :D.
