### ISSUE TITLE
Dependency on starlark fails to resolve

### ISSUE THREAD

**Issue by jsgf** [facebookexperimental/starlark-rust#2]
I added a dependency on starlark-rust:
```
starlark = { git = "https://github.com/facebookexperimental/starlark-rust.git", optional = true }
```
but this fails to resolve with:
```
[jeremy@aerolith reindeer]$ cargo +nightly check 
    Updating git repository `https://github.com/facebookexperimental/starlark-rust.git`
    Updating crates.io index
    Updating git repository `https://github.com/facebookincubator/gazebo`
error: failed to select a version for `syn`.
    ... required by package `starlark_module v0.4.0-pre (https://github.com/facebookexperimental/starlark-rust.git#bf2f90dd)`
    ... which is depended on by `starlark v0.4.0-pre (https://github.com/facebookexperimental/starlark-rust.git#bf2f90dd)`
    ... which is depended on by `reindeer v0.0.0 (/home/jeremy/git/reindeer)`
versions that meet the requirements `^1.0.57` are: 1.0.60, 1.0.59, 1.0.58, 1.0.57

all possible versions conflict with previously selected packages.

  previously selected package `syn v1.0.33`
    ... which is depended on by `auto_impl v0.4.1`
    ... which is depended on by `tower-lsp v0.13.3`
    ... which is depended on by `starlark v0.4.0-pre (https://github.com/facebookexperimental/starlark-rust.git#bf2f90dd)`
    ... which is depended on by `reindeer v0.0.0 (/home/jeremy/git/reindeer)`

failed to select a version for `syn` which could resolve this conflict
```

which seems to be a version conflict on `syn` between tokio-lsp and starlark_module. I don't see this when I build in the starlark-rust repo itself, so I'm not sure why I'm seeing it here - perhaps there's another version of syn involved via one of my other dependencies.

**Comment by ndmitchell** [comment]
The requirement for 1.0.57 is just because that's what I tested starlark_module with. I just tested and it's easy to drop that requirement down to 1.0.33. I've started the process of submitting a patch for that, which needs approval then it can arrive in this repo.

**Comment by ndmitchell** [comment]
Looking at the resolve chain, tower-lsp 0.13.3 is the latest. The depends on auto_impl 0.4, of which 0.4.1 is the latest. That has the bound on syn of ^1.0. So I don't see an inherent conflict. Is it possible that deleting your Cargo.lock will cause it to plan in a more holistic manner, and thus consider all suitable packages when resolving syn?

**Comment by jsgf** [comment]
Hm, deleting and re-creating Cargo.lock did fix it. I guess I'd classify this as a Cargo bug then.

OTOH, splitting out the lsp/binary into a separate package would help thin out downstream dependencies anyway (at least as a workaround to having separate binary deps).

**Comment by ndmitchell** [comment]
Internally we had a big discussion about that. The reason for leaving them included (even though that pulls in tokio, which is a big dependency) is that Starlark is an extensible language - you write new objects and functions in Rust. That means the LSP really wants to be moved into the library, and parameterised by the things you extend it with, so you can have a high-fidelity LSP experience. As an example, currently the LSP can't warn when you use an undefined variable, because it doesn't know the set of variables. It also can't follow load statements since that's embedding specific. Fixing that would cause LSP to be a dependency of the library, and then splitting the binary into a separate package does little.

When it gets to the forthcoming debugger, it's even worse. While you can get 70% quality LSP, you can't get a debugger at all. That has to be in the library, and then wired in with the environment for each project that embeds Starlark.

The plan to avoid dependency creep for those who didn't want it was then to have features - dap and lsp - that exclude those features and a large chunk of dependencies. Plan was to add those when users wanted them though, rather than in advance. Does that all sound plausible?
