### ISSUE TITLE
How should FileLoader::load be implemented?

### ISSUE THREAD

**Issue by anp** [facebookexperimental/starlark-rust#8]
The function's signature accepts `&self` and returns `&FrozenModule`, which I'm not sure how to satisfy with a loader that actually hits the filesystem. If `FileLoader::load` took `&mut self`, I could cache the module in a map in the loader and return a reference to that. If it returned an owned `FrozenModule` then that implementation would be obvious (load the file, parse the ast module, evaluate, freeze, return). 

It looks like the only implementors of the trait in this repo work with already-constructed values. Is there a trick to implementing this with some kind of interning I haven't thought of? Or should the API be changed? If the latter, happy to send a PR.

**Comment by ndmitchell** [comment]
Great question. I've got a diff which gives a worked example, but it's not yet hit the repo (should do by later today). The approach is basically:

```rust
let mut loads = Vec::new();
for load in ast.loads() {
     loads.push((load.to_owned(), get_module(load)?));
}
let modules = loads.iter().map(|(a, b)| (a.as_str(), b)).collect();
let loader = ReturnFileLoader { modules: &modules };
```

So instead of loading the statements as they are hit, use `ast.loads()` in advance to get a list of all load statements that _will_ be hit, shove them into a `HashMap` and use `ReturnFileLoader`. That gives you somewhere to put the ownership.

However, I agree that what you are doing _should_ be easy, and with the above API, it isn't that easy. So I've made two further changes (again, should both land later today):

1. `FileLoader` now returns an owned FrozenValue (cloning them is cheap, so might as well always return an owned variant).
2. `FileLoader` takes a `&mut self`. You probably want to ensure each file is loaded only once, so having a `&mut` here is very helpful.

I'll ping once these two changes make it to the repo.

**Comment by ndmitchell** [comment]
All patches landed:

* There's a demo of using load, 193c188792685f76c4b03ad4312c1f8cc0e12c7b
* I made FileLoader return an owned FrozenModule, be1db2cf93ffa1fa3ed2080db3ff499f74a8fe8c
* I made FileLoader take a &mut self, 964cab71c446bc3d6795788e0d360898c3ac9a7a

Does that solve the issue?

**Comment by ndmitchell** [comment]
Closing, but please reopen if anything remains unclear!

**Comment by anp** [comment]
This seems perfect, thanks! Will post back if I find any issues when trying it out.
